name: Code Formatter

on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd client
      - run: npm install
      - run: npm run code-formatter-check
